#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const {
  SUPPORTED_PLATFORMS,
  readAgencyCatalog,
  resolveSelection
} = require('./agency-catalog');

const GENERATOR = 'harness-everything/multi-agent-workspace';
const ZONES = Object.freeze(['state', 'logs', 'decisions', 'domain', 'architecture', 'roles']);

// Ships standalone (copied whole into every install target), so it can't
// import the source repo's scripts/lib/workspace.js. Only used as the
// --workspace default below - without it, an invocation from a nested
// non-git directory with no explicit --workspace would scatter a fresh
// .harness/multi-agent/ tree right there instead of at the project root
// (issue #42).
function getWorkspaceRoot() {
  let dir = path.resolve(process.cwd());
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function values(args, name) {
  const result = [];
  for (let i = 0; i < args.length; i++) if (args[i] === name) {
    if (!args[i + 1] || args[i + 1].startsWith('--')) throw new Error(`${name} requires a value`);
    result.push(args[++i]);
  }
  return result;
}

function commaValues(args, name) {
  return values(args, name).flatMap(value => value.split(',')).map(value => value.trim()).filter(Boolean);
}

function parseArgs(args) {
  if (args.includes('--help') || args.includes('-h')) return { help: true };
  const workspace = values(args, '--workspace')[0] || getWorkspaceRoot();
  const sourceValues = values(args, '--agency-source');
  const platform = values(args, '--platform')[0] || null;
  if (platform && !SUPPORTED_PLATFORMS.includes(platform)) {
    throw new Error(`unsupported platform "${platform}"; supported: ${SUPPORTED_PLATFORMS.join(', ')}`);
  }
  return {
    workspace: path.resolve(workspace),
    source: sourceValues[0] || process.env.AGENCY_AGENTS_SOURCE || null,
    platform,
    divisions: commaValues(args, '--division'),
    agents: commaValues(args, '--agent'),
    allAgents: args.includes('--all-agents'),
    expectedRevision: values(args, '--expected-agency-revision')[0] || null,
    allowSourceDrift: args.includes('--allow-source-drift'),
    force: args.includes('--force')
  };
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function readExistingManifest(outputRoot) {
  const file = path.join(outputRoot, 'manifest.json');
  if (!fs.existsSync(file)) return null;
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); }
  catch (error) { throw new Error(`existing manifest is invalid: ${error.message}`); }
}

function detectStack(workspaceRoot) {
  const files = fs.readdirSync(workspaceRoot, { withFileTypes: true });
  const names = new Set(files.filter(entry => entry.isFile()).map(entry => entry.name));
  if (names.has('package.json')) return 'node';
  if (names.has('pyproject.toml') || names.has('requirements.txt')) return 'python';
  if (names.has('Cargo.toml')) return 'rust';
  if (names.has('go.mod')) return 'go';
  return 'polyglot';
}

function gitRevision(root) {
  if (!fs.existsSync(path.join(root, '.git'))) return null;
  try { return execFileSync('git', ['-C', root, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim(); }
  catch { return null; }
}

function renderRouter(manifest) {
  const agencyLine = manifest.agency.status === 'available'
    ? `Agency catalog: ${manifest.agency.agentCount} agents in ${manifest.agency.divisionCount} divisions; load selected roles only.`
    : `Agency catalog unavailable: ${manifest.agency.reason}`;
  return `# Multi-Agent Workspace Router

This router is generated by ${GENERATOR}. Sub-agents MUST NOT modify this file.

## Bootstrap Protocol
1. Read the task payload, then \`.harness/multi-agent/state/\`.
2. Read only the relevant decision and architecture records.
3. Load the launcher and selected roles before delegating.
4. Return a structured handoff with changed files and verification evidence.

## Boundaries
- Write working state to \`.harness/multi-agent/state/\`; keep raw output in \`.harness/multi-agent/logs/\`.
- Treat \`.harness/multi-agent/architecture/\` and this router as immutable contracts.
- Delegate only the scope named in the launcher; never preload the external roster.
- If a specialist fails, report the failure and use a bounded fallback or human escalation.

## Catalog
${agencyLine}
`;
}

function renderLauncher(manifest, selectedAgents) {
  const lines = [
    '# Multi-Agent Launcher',
    '',
    `Generator: ${GENERATOR}`,
    `Platform: ${manifest.platform || 'generic'}`,
    `Stack: ${manifest.stack}`,
    '',
    '## Dispatch Contract',
    '',
    'The orchestrator owns sequencing, scope assignment, retries, and final verification.',
    'Each specialist receives one bounded brief and returns a structured handoff.',
    'Load source bodies on demand; this workspace stores metadata, not an unreviewed roster copy.',
    `Converter targets: ${(manifest.agency.converterTargets || []).join(', ') || 'none configured'}.`,
    '',
    '## Selected Specialists',
    ''
  ];
  if (selectedAgents.length === 0) {
    lines.push('- None selected. Search `roles/agency-catalog.json` and rerun the scaffold with `--agent` or `--division`.');
  } else {
    for (const agent of selectedAgents) {
      lines.push(`- **${agent.name}** [${agent.division}] - ${agent.description}`);
      lines.push(`  - slug: \`${agent.slug}\`; source file: \`${agent.sourceFile}\``);
      lines.push('  - boundary: only the files and deliverables named in the dispatch brief.');
    }
  }
  lines.push('', '## Handoff Schema', '', 'Return `status`, `changes`, `verification`, `risks`, and `nextAction`; a failed verification is not a successful handoff.', '');
  return lines.join('\n');
}

function planArtifacts(outputRoot, manifest, catalog, selectedAgents) {
  const catalogPayload = catalog
    ? { ...catalog, generatedBy: GENERATOR }
    : { generatedBy: GENERATOR, status: 'unavailable', agents: [], divisions: [], reason: manifest.agency.reason };
  const artifacts = [
    ['manifest.json', json(manifest)],
    ['AGENTS.md', renderRouter(manifest)],
    ['launcher.md', renderLauncher(manifest, selectedAgents)],
    ['roles/agency-catalog.json', json(catalogPayload)],
    ['roles/selected-agents.json', json({ selected: selectedAgents })],
    ['handoff.json', json({
      schemaVersion: 1,
      status: selectedAgents.length || manifest.agency.status !== 'available' ? 'ready' : 'selection-required',
      generator: GENERATOR,
      scope: { workspace: '.', root: '.harness/multi-agent', zones: ZONES },
      selectedAgents: selectedAgents.map(agent => agent.slug),
      verification: { catalog: manifest.agency.status, indexer: 'passed' },
      nextAction: selectedAgents.length ? 'dispatch selected specialists with bounded briefs' : 'select specialists or configure AGENCY_AGENTS_SOURCE'
    })],
    ['index_memory.js', fs.readFileSync(path.join(__dirname, 'index_memory.js'))]
  ];
  for (const zone of ZONES) artifacts.push([`${zone}/.gitkeep`, '']);
  return artifacts.map(([relative, content]) => ({ path: path.join(outputRoot, relative), content }));
}

function writeArtifacts(outputRoot, artifacts, force) {
  for (const artifact of artifacts) {
    if (!fs.existsSync(artifact.path)) continue;
    const existing = fs.readFileSync(artifact.path);
    if (!existing.equals(Buffer.isBuffer(artifact.content) ? artifact.content : Buffer.from(artifact.content)) && !force) {
      throw new Error(`generated artifact conflict: ${path.relative(outputRoot, artifact.path)} (use --force only for Harness-owned output)`);
    }
  }
  for (const artifact of artifacts) {
    fs.mkdirSync(path.dirname(artifact.path), { recursive: true });
    fs.writeFileSync(artifact.path, artifact.content);
  }
}

function runIndexer(outputRoot) {
  const indexer = path.join(outputRoot, 'index_memory.js');
  const output = path.join(outputRoot, 'memory-index.md');
  execFileSync(process.execPath, [indexer, '--root', path.dirname(path.dirname(outputRoot)), '--output', output], { stdio: 'pipe' });
  return output;
}

function scaffold(options) {
  if (!fs.existsSync(options.workspace) || !fs.statSync(options.workspace).isDirectory()) {
    throw new Error(`workspace not found: ${options.workspace}`);
  }
  const outputRoot = path.join(options.workspace, '.harness', 'multi-agent');
  const existing = readExistingManifest(outputRoot);
  if (existing && existing.generator !== GENERATOR) throw new Error('existing .harness/multi-agent belongs to another generator');
  const catalog = options.source ? readAgencyCatalog(options.source) : null;
  if (options.expectedRevision && (!catalog || catalog.source.revision !== options.expectedRevision)) {
    throw new Error(`agency source revision mismatch: expected ${options.expectedRevision}, got ${catalog && catalog.source.revision || '(unknown)'}`);
  }
  if (existing && existing.agency && existing.agency.sourceRevision && (!catalog || existing.agency.sourceRevision !== catalog.source.revision) && !options.allowSourceDrift) {
    throw new Error(`agency source revision drift: existing ${existing.agency.sourceRevision}, current ${catalog && catalog.source.revision || '(unavailable)'}; pass --allow-source-drift to refresh`);
  }
  const selection = catalog ? resolveSelection(catalog, options.divisions, options.agents, options.allAgents) : { divisionIds: [], agents: [] };
  if (!catalog && (options.divisions.length || options.agents.length || options.allAgents)) {
    throw new Error('cannot select agency agents without --agency-source or AGENCY_AGENTS_SOURCE');
  }
  const agency = catalog
    ? { status: 'available', ...catalog.source, selectedCount: selection.agents.length, selectionRequired: selection.agents.length === 0 }
    : { status: 'unavailable', reason: 'No agency source configured', requiredConfiguration: '--agency-source <path> or AGENCY_AGENTS_SOURCE', selectedCount: 0, selectionRequired: false };
  const manifest = {
    schemaVersion: 1,
    generator: GENERATOR,
    workspaceRevision: gitRevision(options.workspace),
    stack: detectStack(options.workspace),
    platform: options.platform,
    zones: ZONES,
    supportedPlatforms: SUPPORTED_PLATFORMS,
    agency,
    selectedDivisions: selection.divisionIds,
    selectedAgents: selection.agents,
    artifactPaths: ['AGENTS.md', 'launcher.md', 'index_memory.js', 'memory-index.md', 'manifest.json', 'handoff.json']
  };
  const artifacts = planArtifacts(outputRoot, manifest, catalog, selection.agents);
  writeArtifacts(outputRoot, artifacts, options.force || options.allowSourceDrift);
  const memoryIndex = runIndexer(outputRoot);
  const handoffPath = path.join(outputRoot, 'handoff.json');
  const handoff = JSON.parse(fs.readFileSync(handoffPath, 'utf8'));
  handoff.verification.indexer = 'passed';
  fs.writeFileSync(handoffPath, json(handoff));
  return { outputRoot, manifest, memoryIndex };
}

function usage() {
  return [
    'Usage: node scripts/scaffold.js --workspace <path> [options]',
    '  --agency-source <path>       Read divisions.json and agent frontmatter from this source',
    '  --division <id[,id]>         Select every specialist in a division (repeatable)',
    '  --agent <slug[,name]>        Select named specialists (repeatable)',
    '  --all-agents                 Explicitly select the complete metadata catalog',
    '  --platform <name>            Validate a supported converter target',
    '  --allow-source-drift         Accept a different source revision on refresh',
    '  --force                      Overwrite only existing Harness-owned artifacts'
  ].join('\n');
}

function main() {
  try {
    const options = parseArgs(process.argv.slice(2));
    if (options.help) return console.log(usage());
    const result = scaffold(options);
    console.log(`Multi-agent workspace written to ${result.outputRoot}`);
    console.log(`  Zones: ${result.manifest.zones.length}`);
    console.log(`  Agency: ${result.manifest.agency.status}`);
    console.log(`  Selected agents: ${result.manifest.selectedAgents.length}`);
    console.log(`  Memory index: ${result.memoryIndex}`);
  } catch (error) {
    console.error(`ERROR: ${error.message}`);
    process.exitCode = 1;
  }
}

if (require.main === module) main();
module.exports = { GENERATOR, ZONES, parseArgs, scaffold, usage };
